
const $=i=>document.getElementById(i),inr=n=>'₹'+n.toLocaleString('en-IN');
const art=(a,b,k=0)=>{const s=`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 500' preserveAspectRatio='xMidYMid slice'><defs><linearGradient id='g' x1='0' y1='0' x2='0' y2='1'><stop offset='0' stop-color='${a}'/><stop offset='1' stop-color='${b}'/></linearGradient></defs><rect width='400' height='500' fill='url(%23g)'/><circle cx='${280-k*40}' cy='${130+k*20}' r='42' fill='%23ffe9a8' opacity='.85'/><path d='M0 330L90 210l70 90 60-70 90 110 90-80v250H0z' fill='%23000' opacity='.22'/><path d='M0 390Q100 330 200 380T400 360V500H0z' fill='%23000' opacity='.35'/><path d='M0 440Q120 400 240 440T400 420V500H0z' fill='%23fff' opacity='.18'/></svg>`;return 'url(data:image/svg+xml,'+encodeURIComponent(s.replace(/%23/g,'#')).replace(/'/g,'%27').replace(/\(/g,'%28').replace(/\)/g,'%29')+')'};
const pic=(d,k)=>IMG[d[0]]?`url('${IMG[d[0]]}'),${art(...d[3],k)}`:art(...d[3],k);
const D=[["Tirupati","Andhra Pradesh","Sacred hill temple of Lord Venkateswara",["#f6a04d","#7a2d0f"]],["Srisailam","Andhra Pradesh","Jyotirlinga temple on the Nallamala hills",["#e08a5a","#4a2a1a"]],["Varanasi","Uttar Pradesh","Ghats and evening aarti on the Ganga",["#f2b66d","#5a3a2a"]],["Rameswaram","Tamil Nadu","Island temple town with long corridors",["#4fc3d9","#124e66"]],["Araku Valley","Andhra Pradesh","Coffee hills, mist and tribal culture",["#7fd69a","#0f5a3a"]],["Munnar","Kerala","Rolling tea estates above the clouds",["#8fe0a0","#1c6a4a"]],["Ooty","Tamil Nadu","Nilgiri hill station with toy train",["#9ad7b8","#2a5a6a"]],["Coorg","Karnataka","Coffee plantations and forest trails",["#6fcf8a","#154a2a"]],["Dudhsagar Falls","Goa","Four-tier waterfall on the Goa border",["#7fd0ee","#12506a"]],["Manali","Himachal Pradesh","Snow peaks, pine valleys and river rafting",["#b7d9f0","#2a4a7a"]],["Kashmir","Jammu & Kashmir","Lakes, meadows and Himalayan views",["#a8d8ee","#34507a"]],["Hampi","Karnataka","Boulder landscape with Vijayanagara ruins",["#e5b070","#6a3a1a"]]];
const C=["Temple & Spiritual","Waterfalls & Nature","Mountains & Hill Stations","Greenery & Forest","Beach & Coastal","Bus Packages","Weekend Getaways","Family Holidays","Adventure & Trekking","Heritage & Cultural"];
const CI=[0,8,9,5,3,0,4,7,9,11],dc=n=>D.find(d=>d[0]==n)||D[0],dart=(n,k)=>pic(dc(n),k);
// central demo data
const T=[["Tirupati Temple Darshan","Hyderabad","Tirupati",0,2,2499,"AC","Sleeper","2026-11-14",4.6,212,90],["Araku Valley Nature Tour","Visakhapatnam","Araku Valley",1,2,2199,"AC","Seater","2026-11-08",4.5,148,80],["Srisailam Temple Tour","Hyderabad","Srisailam",0,1,1499,"AC","Seater","2026-11-02",4.4,96,70],["Munnar Green Valley Tour","Bengaluru","Munnar",3,3,4999,"AC","Sleeper","2026-11-21",4.7,178,85],["Dudhsagar Waterfall Tour","Hyderabad","Dudhsagar Falls",1,2,2999,"AC","Seater","2026-12-05",4.3,87,60],["Varanasi Kashi Yatra","Delhi","Varanasi",0,3,4499,"AC","Sleeper","2026-11-18",4.6,131,75],["Rameswaram Pilgrim Package","Chennai","Rameswaram",0,2,2799,"Non-AC","Seater","2026-11-12",4.2,64,55],["Coorg Coffee Weekend","Bengaluru","Coorg",6,2,3299,"AC","Seater","2026-11-07",4.5,102,68],["Ooty Family Holiday","Chennai","Ooty",7,3,4199,"Non-AC","Sleeper","2026-12-01",4.4,73,58],["Manali Snow Escape","Delhi","Manali",2,3,5799,"AC","Sleeper","2026-12-12",4.8,205,92],["Kashmir Meadows Trip","Delhi","Kashmir",2,3,5999,"AC","Sleeper","2026-12-20",4.7,119,72],["Hampi Heritage Trail","Bengaluru","Hampi",9,2,2399,"Non-AC","Seater","2026-11-15",4.5,88,64],["Kochi Backwater Bus Pack","Kochi","Munnar",5,1,1899,"AC","Seater","2026-11-09",4.1,52,50],["Jaipur Heritage Tour","Delhi","Hampi",9,2,3599,"AC","Seater","2026-11-26",4.3,61,52]].map((r,i)=>({id:i,name:r[0],from:r[1],dest:r[2],cat:r[3],days:r[4],price:r[5],ac:r[6],seat:r[7],date:r[8],rating:r[9],rev:r[10],pop:r[11],total:r[7]=="Sleeper"?24:40,booked:[...Array(r[7]=="Sleeper"?24:40).keys()].filter(n=>(n*7+i*5)%5<2&&n%3!=0)}));
T[13].name="Jaipur Pink City Heritage";T[13].dest="Hampi";
let store;try{store=JSON.parse(localStorage.getItem('wb'))}catch(e){}store=store||{u:null,b:[],s:[]};const save=()=>{try{localStorage.setItem('wb',JSON.stringify(store))}catch(e){}};try{}catch(e){}
const avail=t=>t.total-t.booked.length;
function toast(m){const e=$('toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',2400)}
function route(){const h=location.hash.slice(1)||'home';document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));nl.classList.remove('open');
const L=['tours','bus','temple','nature'].includes(h)||h.startsWith('d:')||h.startsWith('c:');$(L?'p-list':h=='bookings'?'p-bookings':'p-home').classList.add('on');
nav.classList.toggle('solid',L||h=='bookings');document.querySelectorAll('.nl a').forEach(a=>a.classList.toggle('on',a.getAttribute('href')=='#'+h));
if(L){const m={tours:['Explore Tours','All departures from across India.'],bus:['Bus Tours','Comfortable AC and non-AC bus packages.'],temple:['Temple Tours','Respectful pilgrimage packages. Follow temple dress code and timings.'],nature:['Nature, Waterfalls & Hills','Greenery, waterfalls, beaches and mountains.']}[h]||[h.startsWith('d:')?h.slice(2):C[+h.slice(2)],h.startsWith('d:')?dc(h.slice(2))[2]:'Tours in this category'];$('lt').textContent=m[0];$('ls').textContent=m[1];
if(h=='temple')fc.value=C[0];else if(h=='nature')fc.value=C[1];else if(h.startsWith('c:'))fc.value=C[+h.slice(2)];else if(h.startsWith('d:'))fd.value=h.slice(2);else if(h=='bus')fc.value=C[5];else if(['temple','nature'].every(x=>x!=h)&&h=='tours'){}
if(h=='bus'){fc.value=''};render()}
if(h=='bookings')renderBk();scrollTo(0,0)}
addEventListener('hashchange',route);addEventListener('scroll',()=>nav.classList.toggle('sc',scrollY>40));
const opt=(a,f)=>`<option value="">${f}</option>`+a.map(x=>`<option>${x}</option>`).join('');
function init(){const cities=[...new Set(T.map(t=>t.from))].concat(['Mumbai','Jaipur']);$('cities').innerHTML=cities.map(c=>`<option>${c}</option>`).join('');$('dl').innerHTML=D.map(d=>`<option>${d[0]}</option>`).join('');
$('sc').innerHTML=opt(C,'Any category');fc.innerHTML=opt(C,'Any');fd.innerHTML=opt(D.map(d=>d[0]),'Any');ff.innerHTML=opt([...new Set(T.map(t=>t.from))],'Any');
$('cats').innerHTML=C.map((c,i)=>`<button class="cat ${i>2?'x':''}" onclick="location.hash='c:${i}'"><div class="im" style="background-image:${pic(D[CI[i]],i%3)}"></div><div class="tx"><b>${c}</b><small>${T.filter(t=>t.cat==i).length} demo tours · Explore</small></div></button>`).join('');
$('dgrid').innerHTML=D.map((d,i)=>{const n=T.filter(t=>t.dest==d[0]);return`<div class="tc ${i>2?'x':''}"><div class="ph" style="background-image:${pic(d,i%3)};background-size:cover"></div><div class="bd"><h3>${d[0]}</h3><div class="meta">${d[1]}</div><div class="meta">${d[2]}</div><div class="meta">${n.length?n.length+' tours from '+inr(Math.min(...n.map(t=>t.price))):'Tours coming soon'}</div><div class="ac"><button class="btn s" onclick="location.hash='d:${d[0]}'">View Tours</button><button class="btn l s" onclick="saveD('${d[0]}')">${store.s.includes(d[0])?'♥ Saved':'♡ Save'}</button></div></div></div>`}).join('');
$('cats').insertAdjacentHTML('beforeend',vm('cats'));$('dgrid').insertAdjacentHTML('beforeend',vm('dgrid'));$('rev').innerHTML=[["Anita R.","Smooth overnight bus and a well-paced itinerary.",5],["Vikram S.","Good value for the temple package.",4],["Meera K.","Loved the valley views. Seats were comfortable.",5]].map(r=>`<div class="box"><b>${r[0]}</b> <span style="color:var(--o)">${'★'.repeat(r[2])}</span><p>${r[1]}</p><small class="sample">Sample content</small></div>`).join('');
document.querySelectorAll('#fl select,#fl input').forEach(e=>e.addEventListener('input',()=>{$('bv').textContent=fb.value;render()}));buildCar();route()}
function saveD(n){const i=store.s.indexOf(n);i<0?store.s.push(n):store.s.splice(i,1);save();init2();toast(i<0?'Saved '+n:'Removed '+n)}
function init2(){const sc=scrollY;init();scrollTo(0,sc)}
function doSearch(){clr(1);if(sd.value){const d=D.find(x=>x[0].toLowerCase()==sd.value.toLowerCase());fd.value=d?d[0]:''}ff.value=[...ff.options].some(o=>o.value==sf.value)?sf.value:'';fc.value=sc.value;fdt.value=sdt.value;
$('load').style.display='block';$('tg').innerHTML='';$('lt').textContent='Search results';location.hash='tours';setTimeout(()=>{$('load').style.display='none';render()},500)}
function clr(k){['fd','ff','fc','fdt','fdu','fa','fs'].forEach(i=>$(i).value='');fb.value=6000;bv.textContent=6000;fav.checked=false;so.value='pop';if(!k){sf.value=sd.value=sdt.value=srt.value='';sc.value='';if(location.hash!='#tours'){location.hash='tours'}else render()}}
function render(){let r=T.filter(t=>(!fd.value||t.dest==fd.value)&&(!ff.value||t.from==ff.value)&&(!fc.value||C[t.cat]==fc.value||(fc.value==C[5]&&t.ac))&&(!fdt.value||t.date>=fdt.value)&&t.price<=+fb.value&&(!fdu.value||(fdu.value==3?t.days>=3:t.days==fdu.value))&&(!fa.value||t.ac==fa.value)&&(!fs.value||t.seat==fs.value)&&(!fav.checked||avail(t)>0));
const h=location.hash.slice(1);if(h=='temple')r=r.filter(t=>t.cat==0);if(h=='nature')r=r.filter(t=>[1,2,3,4].includes(t.cat));
r.sort((a,b)=>so.value=='pl'?a.price-b.price:so.value=='ph'?b.price-a.price:so.value=='du'?b.days-a.days:b.pop-a.pop);
$('tg').innerHTML=r.length?r.map(tc).join(''):`<div class="box" style="grid-column:1/-1"><b>No tours match these filters.</b><p>Try a wider budget, a different city, or clear filters.</p><button class="btn" onclick="clr()">Clear filters</button></div>`}
function tc(t){return`<div class="tc"><div class="ph" style="background-image:${dart(t.dest,t.id%3)};background-size:cover"><span class="tag">${C[t.cat]}</span></div><div class="bd"><h3>${t.name}</h3><div class="meta">${t.from} → ${t.dest}</div><div class="meta">${t.days}D${t.days>1?'/'+(t.days-1)+'N':''} · ${t.ac} ${t.seat} bus · ${t.date}</div><div class="meta">★ ${t.rating} (${t.rev}) <span class="sample">demo</span></div><div class="meta">${avail(t)} of ${t.total} seats left</div><div class="price">${inr(t.price)} <small style="font-size:12px;font-weight:400">/person</small></div><div class="ac"><button class="btn l" onclick="detail(${t.id})">View Details</button><button class="btn o" onclick="book(${t.id})">Book Now</button></div></div></div>`}
function openM(h){$('mc').innerHTML=h;mod.classList.add('on')}function closeM(){mod.classList.remove('on')}
mod.addEventListener('click',e=>{if(e.target==mod)closeM()});addEventListener('keydown',e=>e.key=='Escape'&&closeM());
function detail(i){const t=T[i],rel=T.filter(x=>x.id!=i&&(x.cat==t.cat||x.dest==t.dest)).slice(0,3);
openM(`<div class="gal"><div style="background-image:${dart(t.dest,0)}"></div><div style="display:grid;gap:6px"><div style="background-image:${dart(t.dest,1)}"></div><div style="background-image:${dart(t.dest,2)}"></div></div></div><p class="meta">Photos: Creative-Commons images via LoremFlickr (demo). Use your own licensed photos for production.</p><h2 style="margin:6px 0">${t.name}</h2><div class="meta">${C[t.cat]} · ${t.from} → ${t.dest} · ${t.days} day(s) · ${t.ac} ${t.seat}</div>
<div class="two" style="margin:14px 0"><div class="box"><b>Itinerary</b><p><b>Day 1:</b> Evening pickup at ${t.from}, overnight/day travel with rest stops.</p>${t.days>1?`<p><b>Day 2:</b> Sightseeing at ${t.dest}, local lunch, return journey.</p>`:''}${t.days>2?'<p><b>Day 3:</b> Leisure, viewpoints and shopping, then departure.</p>':''}</div>
<div class="box"><b>Pickup &amp; timings</b><p>${t.from} main bus stand, 8:30 PM (demo).<br>Arrival ${t.dest}: approx. 7:00 AM.<br>Bus: ${t.ac} ${t.seat}, charging point, water bottle.</p></div>
<div class="box"><b>Included / Excluded</b><p>✔ Bus, guide, parking, tolls<br>${t.days>1?'✔ Basic hotel stay<br>':''}✘ Meals, entry tickets, personal expenses</p></div>
<div class="box"><b>Guidelines &amp; cancellation</b><p>Carry photo ID. Dress modestly at temples. Demo policy: free cancel up to 48h before departure.</p></div></div>
<div class="box" style="background:linear-gradient(135deg,#079BA522,#25B9D522);margin-bottom:12px"><b>Map (placeholder)</b>: 📍 ${t.from} → 📍 ${t.dest}</div>
<div class="box"><b>Price breakdown</b><p>Base fare ${inr(Math.round(t.price*.8))} + hotel/guide ${inr(Math.round(t.price*.15))} + taxes ${inr(Math.round(t.price*.05))} = <b>${inr(t.price)}</b> per person · ${avail(t)} seats left</p><button class="btn o" onclick="book(${t.id})">Book Now</button></div>
<h3>Related tours</h3><div class="row">${rel.map(x=>`<button class="btn l s" onclick="detail(${x.id})">${x.name}</button>`).join('')||'None'}</div>`)}
let B={};
function book(i){B={t:T[i],date:T[i].date,n:2,seats:[],step:1,f:{name:store.u?store.u.name:'',mob:'',email:store.u?store.u.email:'',age:'',pick:T[i].from+' main bus stand'},extra:false};bstep()}
function pg(){return`<div class="pg">${[1,2,3,4,5].map(i=>`<i class="${i<=B.step?'on':''}"></i>`).join('')}</div>`}
const total=()=>B.t.price*B.n+(B.extra?250*B.n:0);
function bstep(){const t=B.t;let h=`<h3 style="margin:0 0 4px">Book: ${t.name}</h3><p class="meta"><b>DEMO ONLY</b> – no real booking or payment.</p>${pg()}`;
if(B.step==1)h+=`<div class="fg2"><div><label>Departure date</label><input type="date" id="bd" value="${B.date}"></div><div><label>Travellers</label><input type="number" id="bn" min="1" max="6" value="${B.n}"></div></div><p>Fare ${inr(t.price)} × <span id="bnn">${B.n}</span> = <b id="bt">${inr(total())}</b></p><button class="btn o" onclick="B.date=bd.value||B.date;B.n=Math.max(1,Math.min(6,+bn.value||1));B.seats=[];B.step=2;bstep()">Continue to seats</button>`;
if(B.step==2){h+=`<p>Select <b>${B.n}</b> seat(s). <span class="sample">Simulated availability (local only)</span></p><div class="lg"><span><i style="background:var(--p)"></i>Available</span><span><i style="background:var(--o)"></i>Selected</span><span><i style="background:#9aa"></i>Booked</span></div><div class="bus"><div class="meta" style="text-align:right">🚌 Driver ⊙</div>${seatmap()}</div><div class="meta" style="text-align:center">Total ${t.total} · Available ${avail(t)} · Selected ${B.seats.map(s=>s+1).join(', ')||'–'} · Fare/seat ${inr(t.price)} · <b>Total ${inr(t.price*B.seats.length)}</b></div><div class="row"><button class="btn l" onclick="B.step=1;bstep()">Back</button><button class="btn o" onclick="if(B.seats.length!=B.n)return toast('Select exactly '+B.n+' seat(s)');B.step=3;bstep()">Continue</button></div>`}
if(B.step==3){const f=B.f;h+=`<div class="fg2"><div class="w"><label>Full name</label><input id="fn" value="${f.name}"></div><div><label>Mobile (10 digits)</label><input id="fm" value="${f.mob}" inputmode="numeric"></div><div><label>Email</label><input id="fe" value="${f.email}"></div><div><label>Age (lead traveller)</label><input id="fa2" type="number" value="${f.age}"></div><div><label>Pickup location</label><select id="fp"><option>${t.from} main bus stand</option><option>${t.from} railway station</option></select></div><div class="w"><span class="err" id="er"></span></div></div><div class="row"><button class="btn l" onclick="B.step=2;bstep()">Back</button><button class="btn o" onclick="det()">Continue</button></div>`}
if(B.step==4)h+=`<div class="box"><p>${t.name}<br>${B.date} · ${B.n} traveller(s) · Seats ${B.seats.map(s=>s+1).join(', ')}</p><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" style="width:auto" ${B.extra?'checked':''} onchange="B.extra=this.checked;bstep()">Travel insurance + meals add-on (${inr(250)}/person)</label><p>Tour ${inr(t.price*B.n)}${B.extra?' + add-on '+inr(250*B.n):''}<br><b style="font-size:20px">Total ${inr(total())}</b></p></div><p><b>Simulated payment</b> (no money is charged)</p><div class="row">${['UPI (demo)','Card (demo)','Net banking (demo)'].map(x=>`<label style="display:flex;gap:6px;align-items:center"><input type="radio" name="pm" style="width:auto" checked>${x}</label>`).join('')}</div><div class="row"><button class="btn l" onclick="B.step=3;bstep()">Back</button><button class="btn o" onclick="confirmB()">Confirm demo booking</button></div>`;
if(B.step==5)h=`<h3>✔ Demo booking confirmed</h3>`+ticket(B.bk)+`<div class="row"><button class="btn" onclick="window.print()">Print Booking</button><button class="btn l" onclick="closeM();location.hash='bookings'">My Bookings</button></div>`;
openM(h);if(B.step==1){bd.oninput=bn.oninput=()=>{const n=Math.max(1,+bn.value||1);bnn.textContent=n;bt.textContent=inr(t.price*n)}}}
function seatmap(){const t=B.t,sl=t.seat=="Sleeper",per=sl?3:4,rows=t.total/per;let h='';for(let r=0;r<rows;r++){h+='<div class="sr">';for(let c=0;c<per;c++){const n=r*per+c,bk=t.booked.includes(n),s=B.seats.includes(n);h+=`<button class="seat ${sl?'sl':''} ${bk?'b':s?'s':''}" ${bk?'disabled':''} onclick="pick(${n})" aria-label="Seat ${n+1}">${n+1}</button>`;if(c==(sl?0:1))h+='<span class="ai"></span>'}h+='</div>'}return h}
function pick(n){const i=B.seats.indexOf(n);if(i>=0)B.seats.splice(i,1);else if(B.seats.length<B.n)B.seats.push(n);else return toast('Max '+B.n+' seats – deselect one first');bstep()}
function det(){const f=B.f;f.name=fn.value.trim();f.mob=fm.value.trim();f.email=fe.value.trim();f.age=fa2.value;f.pick=fp.value;
const e=!f.name?'Enter your full name.':!/^[6-9]\d{9}$/.test(f.mob)?'Enter a valid 10-digit Indian mobile number.':!/^\S+@\S+\.\S+$/.test(f.email)?'Enter a valid email.':'';if(e){er.textContent=e;return}B.step=4;bstep()}
function confirmB(){const ref='WB'+Date.now().toString(36).toUpperCase().slice(-6);B.bk={ref,tid:B.t.id,date:B.date,n:B.n,seats:B.seats,f:B.f,total:total(),st:'confirmed'};store.b.unshift(B.bk);B.t.booked.push(...B.seats);save();B.step=5;bstep()}
function ticket(b){const t=T[b.tid];return`<div class="tk"><b style="font-size:18px">${t.name}</b> <span class="sample">DEMO TICKET</span><p class="meta">Ref <b>${b.ref}</b> · ${b.date}<br>${t.from} → ${t.dest} · ${t.ac} ${t.seat}<br>Passenger: ${b.f.name} (${b.f.mob}) · Pickup: ${b.f.pick}<br>Seats: ${b.seats.map(s=>s+1).join(', ')} · Travellers: ${b.n}</p><b>Total ${inr(b.total)}</b><p class="meta">Not a valid travel document. Simulated only.</p></div>`}
function renderBk(){const b=store.b,today=new Date().toISOString().slice(0,10);
const card=x=>{const t=T[x.tid],up=x.st=='confirmed'&&x.date>=today,lab=x.st=='cancelled'?'Cancelled':up?'Confirmed':'Completed';return`<div class="bc"><div class="bi" style="background-image:${dart(t.dest,0)}"></div><div class="bm"><div class="bt"><b>${t.name}</b><span class="bd2 ${x.st=='cancelled'?'rd':up?'gn':'gy'}">${lab}</span></div><div class="meta">${t.from} → ${t.dest} · ${x.n} traveller(s)</div><div class="meta">Ref <b>${x.ref}</b> · ${x.date}</div><div class="bp">${inr(x.total)}</div></div><div class="ba"><button class="btn l s" onclick="viewBk('${x.ref}')">Details</button>${up?`<button class="btn s" onclick="cancelBk('${x.ref}')">Cancel</button>`:''}</div></div>`};
const g=(l,ic,a,msg)=>`<div class="bs"><h2>${l} <span class="cnt">${a.length}</span></h2>${a.length?a.map(card).join(''):`<div class="ph2"><div class="ico">${ic}</div><b>${msg}</b><p class="meta">Pick a destination, choose your seats and your trip will show up here.</p><button class="btn o" onclick="location.hash='tours'">Book Now</button></div>`}</div>`;
const prof=store.u?`<div class="pc"><div class="av">${store.u.name.trim()[0].toUpperCase()}</div><div class="pi"><b>${store.u.name}</b><div class="meta">${store.u.email}${store.u.g?' · Google':''}</div></div><div class="ba"><button class="btn l s" onclick="editP()">Edit profile</button><button class="btn s" onclick="logout()">Logout</button></div></div>`:`<div class="pc lo"><div class="pi"><b>Log in to see your trips</b><div class="meta">Attach bookings to a profile and keep everything in one place.</div></div><div class="ba"><button class="btn o" onclick="authM()">Login</button><button class="btn l" onclick="authM('up')">Sign up</button></div></div>`;
const sv=store.s.length?`<div class="row" style="margin:0;justify-content:center">${store.s.map(s=>`<button class="btn l s" onclick="location.hash='d:${s}'">♥ ${s}</button>`).join('')}</div>`:`<div class="ph2"><div class="ico">♡</div><b>No saved destinations</b><p class="meta">Tap ♡ Save on any destination card to keep it here.</p><button class="btn o" onclick="location.hash='tours'">Explore Tours</button></div>`;
$('bk').innerHTML=prof+g('Upcoming trips','🚌',b.filter(x=>x.st=='confirmed'&&x.date>=today),'No upcoming trips yet')+g('Past trips','🧳',b.filter(x=>x.st=='confirmed'&&x.date<today),'No past trips')+g('Cancelled','✕',b.filter(x=>x.st=='cancelled'),'No cancelled bookings')+`<div class="bs"><h2>Saved destinations <span class="cnt">${store.s.length}</span></h2>${sv}</div>`}
const viewBk=r=>openM(ticket(store.b.find(x=>x.ref==r))+'<div class="row"><button class="btn" onclick="window.print()">Print</button></div>');
function cancelBk(r){const b=store.b.find(x=>x.ref==r);b.st='cancelled';T[b.tid].booked=T[b.tid].booked.filter(s=>!b.seats.includes(s));save();renderBk();toast('Demo booking cancelled')}
function logout(){store.u=null;save();ui();renderBk()}function ui(){lg.textContent=store.u?'👤 '+store.u.name.split(' ')[0]:'Login / Sign Up';lg.onclick=()=>store.u?(location.hash='bookings'):authM()}
function editP(){openM(`<h3>Edit profile</h3><div class="fg2"><div><label>Name</label><input id="en" value="${store.u.name}"></div><div><label>Email</label><input id="ee" value="${store.u.email}"></div></div><button class="btn o" style="margin-top:12px" onclick="store.u.name=en.value||store.u.name;store.u.email=ee.value||store.u.email;save();ui();closeM();renderBk()">Save changes</button>`)}
const GIC=`<svg width='18' height='18' viewBox='0 0 48 48'><path fill='#EA4335' d='M24 9.5c3.5 0 6.6 1.2 9.1 3.6l6.8-6.8C35.9 2.4 30.4 0 24 0 14.6 0 6.5 5.4 2.6 13.2l7.9 6.1C12.4 13.6 17.7 9.5 24 9.5z'/><path fill='#4285F4' d='M46.5 24.5c0-1.6-.1-3.1-.4-4.5H24v9h12.7c-.6 3-2.3 5.5-4.8 7.2l7.6 5.9c4.4-4.1 7-10.1 7-17.6z'/><path fill='#FBBC05' d='M10.5 28.7c-.5-1.4-.8-3-.8-4.7s.3-3.2.8-4.7l-7.9-6.1C.9 16.4 0 20.1 0 24s.9 7.6 2.6 10.8l7.9-6.1z'/><path fill='#34A853' d='M24 48c6.500 0 11.900-2.100 15.900-5.800l-7.600-5.900c-2.100 1.400-4.900 2.300-8.300 2.300-6.300 0-11.600-4.200-13.500-9.900l-7.900 6.100C6.500 42.600 14.600 48 24 48z'/></svg>`;
function authM(m='in'){const s=m=='up';openM(`<div class="au"><div class="logo2"><svg width="24" height="24" viewBox="0 0 28 28"><rect width="28" height="28" fill="#FFA62B"/><path d="M5 19l6-9 4 6 3-4 5 7z" fill="#073D50"/></svg>Wanderbus India</div>
<h3>${s?'Create your account':'Welcome back'}</h3><p class="sb">${s?'Sign up to save trips and manage bookings.':'Log in to view your bookings and saved destinations.'} <span class="sample">Demo auth</span></p>
<button class="gbtn" onclick="googleLogin()">${GIC}Continue with Google</button><div id="gbox"></div>
<div class="dv">or use email</div>
${s?'<div class="f"><label>Full name</label><input id="an" autocomplete="name" placeholder="Your name"></div><div class="f"><label>Email</label><input id="ae" type="email" autocomplete="email" placeholder="you@example.com"></div><div class="f"><label>Mobile</label><input id="am" inputmode="numeric" maxlength="10" placeholder="10-digit mobile"></div>':'<div class="f"><label>Email or mobile</label><input id="ae" autocomplete="username" placeholder="you@example.com"></div>'}
<div class="f"><label>Password</label><div class="pw"><input id="ap" type="password" autocomplete="${s?'new-password':'current-password'}" placeholder="At least 8 characters"><button type="button" onclick="const t=ap.type=='password';ap.type=t?'text':'password';${s?"ac.type=ap.type;":""}this.textContent=t?'Hide':'Show'">Show</button></div></div>
${s?'<div class="f"><label>Confirm password</label><input id="ac" type="password" autocomplete="new-password"></div><label style="display:flex;gap:6px;align-items:center;font-weight:400;opacity:1;margin-bottom:12px"><input id="at" type="checkbox" style="width:auto">I accept the demo Terms</label>':'<div class="opts"><label><input type="checkbox">Remember me</label><a onclick="toast(\'Reset link (demo)\')">Forgot password?</a></div>'}
<div class="err" id="ar" style="margin-bottom:8px"></div>
<button class="btn o full" onclick="auth(${s})">${s?'Create account':'Login'}</button>
<div class="sw">${s?'Already have an account?':'New here?'} <a onclick="authM('${s?'in':'up'}')">${s?'Login':'Sign up'}</a></div></div>`);
document.querySelectorAll('#mc input').forEach(i=>i.addEventListener('keydown',e=>e.key=='Enter'&&auth(s)))}
function googleLogin(){
 if(typeof GOOGLE_CLIENT_ID!='undefined'&&GOOGLE_CLIENT_ID&&location.protocol!='file:'){
  const go=()=>{google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:r=>{try{const p=JSON.parse(decodeURIComponent(escape(atob(r.credential.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))));store.u={name:p.name||p.email.split('@')[0],email:p.email,pic:p.picture,g:1};save();ui();closeM();toast('Signed in with Google');if(location.hash=='#bookings')renderBk()}catch(e){toast('Google sign-in failed')}}});google.accounts.id.prompt()};
  if(window.google&&google.accounts)return go();
  const sc=document.createElement('script');sc.src='https://accounts.google.com/gsi/client';sc.onload=go;sc.onerror=()=>toast('Could not load Google sign-in');document.head.appendChild(sc);return}
 gAcct()}
function gAcct(){openM(`<div class="au"><div style="text-align:center;margin-bottom:6px">${GIC}</div><h3 style="text-align:center">Choose an account</h3><p class="sb" style="text-align:center">to continue to Wanderbus India <span class="sample">Demo – no real Google login</span></p>
<button class="ga" onclick="gDone('Kittu Naik','kittu@gmail.com')"><i>K</i><span><b>Kittu Naik</b><br><small>kittu@gmail.com</small></span></button>
<button class="ga" onclick="gDone('Demo Traveller','traveller@gmail.com')"><i style="background:var(--o);color:#111">D</i><span><b>Demo Traveller</b><br><small>traveller@gmail.com</small></span></button>
<div class="dv">or</div><div class="f"><label>Use another Google account (email)</label><input id="ge" type="email" placeholder="you@gmail.com"></div><div class="err" id="gr"></div>
<button class="btn full" onclick="const v=ge.value.trim();if(!/^\S+@\S+\.\S+$/.test(v))return gr.textContent='Enter a valid email.';gDone(v.split('@')[0],v)">Next</button><div class="sw"><a onclick="authM()">Back to login</a></div></div>`)}
function gDone(n,e){store.u={name:n,email:e,g:1};save();ui();closeM();toast('Signed in with Google (demo)');if(location.hash=='#bookings')renderBk()}
function auth(s){const id=ae.value.trim(),ok=/^\S+@\S+\.\S+$/.test(id)||/^[6-9]\d{9}$/.test(id);let e=!ok?'Enter a valid email or mobile number.':ap.value.length<8?'Password must be at least 8 characters.':'';
if(s&&!e){e=!an.value.trim()?'Enter your name.':!/^\S+@\S+\.\S+$/.test(id)?'Enter a valid email.':!/^[6-9]\d{9}$/.test(am.value)?'Enter a valid 10-digit mobile.':ac.value!=ap.value?'Passwords do not match.':!at.checked?'Accept the terms to continue.':''}
if(e){ar.textContent=e;return}store.u={name:s?an.value.trim():id.split('@')[0],email:id};save();ui();closeM();toast('Signed in (demo)');if(location.hash=='#bookings')renderBk()}
// carousel
let ci=0,auto,drag=null;const CS=[0,4,5,8,9,2];
function buildCar(){const c=$('car');c.innerHTML=CS.map((d,i)=>`<div class="cc" data-i="${i}"><div class="im" style="background-image:${pic(D[d],i%3)}"></div><div class="tx"><h3>${D[d][0]}</h3><p>${D[d][2]}</p><button class="btn o s" onclick="location.hash='d:${D[d][0]}'">Explore</button></div></div>`).join('');
$('dots').innerHTML=CS.map((_,i)=>`<i onclick="ci=${i};pos();rst()"></i>`).join('');pos();
c.onpointerdown=e=>{drag=e.clientX;clearInterval(auto)};c.onpointerup=e=>{if(drag!=null){const dx=e.clientX-drag;if(Math.abs(dx)>40)go(dx<0?1:-1);drag=null;rst()}};c.onpointerleave=()=>drag=null;
c.onwheel=e=>{if(Math.abs(e.deltaX)>30){e.preventDefault();go(e.deltaX>0?1:-1)}};c.onmouseenter=()=>clearInterval(auto);c.onmouseleave=rst;rst()}
function pos(){const n=CS.length,w=innerWidth<700?1:1;document.querySelectorAll('.cc').forEach((el,i)=>{let o=((i-ci+n)%n);if(o>n/2)o-=n;const a=Math.abs(o),sp=innerWidth<700?55:68;el.style.transform=`translate(calc(-50% + ${o*sp*(a>1?.82:1)}%),calc(-50% - ${o==0?14:0}px)) scale(${o==0?1:a==1?.82:.68}) rotate(${o*5}deg)`;el.style.zIndex=10-a;el.style.opacity=a>2?0:1;el.style.filter=o?'brightness(.75)':'none';el.style.pointerEvents=a>2?'none':'auto'});document.querySelectorAll('#dots i').forEach((d,i)=>d.classList.toggle('on',i==ci))}
function go(d){ci=(ci+d+CS.length)%CS.length;pos();rst()}function rst(){clearInterval(auto);if(!matchMedia('(prefers-reduced-motion:reduce)').matches)auto=setInterval(()=>{ci=(ci+1)%CS.length;pos()},4500)}
if(typeof HERO_BG!='undefined'&&HERO_BG){const im=new Image();im.onload=()=>document.documentElement.style.setProperty('--hb',`url('${HERO_BG}')`);im.src=HERO_BG}
init();ui();addEventListener('resize',pos);


function vm(id){const o=!document.getElementById(id).classList.contains('cl');return `<button class="vm" onclick="more('${id}')"><span>${o?'−':'+'}</span>${o?'Show less':'View more'}</button>`}
function more(id){const e=document.getElementById(id);e.classList.toggle('cl');e.querySelector('.vm').outerHTML=vm(id)}
